### ISSUE TITLE
"TypeError: this.options.changes.startWith is not a function" with Enum

### ISSUE THREAD

**Issue by FoundryFounder** [dschnelldavis/angular2-json-schema-form#62] opened 2017-07-07 15:58 UTC
New to A2JSF.  Trying to do basic example.
I have an enum schema object:
`"status": {
	"type": "string",
	"enum": [
		"Draft",
		"Published"
	],
	"title": "Status"
},`
Whenever I have such an enum, I get this error:
`ERROR TypeError: this.options.changes.startWith is not a function
    at MdSelect.webpackJsonp.../../../../angular2-json-schema-form/angular2-json-schema-form.es5.js.MdSelect.ngAfterContentInit (angular2-json-schema-form.es5.js:50477)
    at callProviderLifecycles (core.es5.js:11234)
    at callElementProvidersLifecycles (core.es5.js:11215)
    at callLifecycleHooksChildrenFirst (core.es5.js:11199)
    at checkAndUpdateView (core.es5.js:12291)
    at callViewAction (core.es5.js:12651)
    at execComponentViewsAction (core.es5.js:12583)
    at checkAndUpdateView (core.es5.js:12294)
    at callViewAction (core.es5.js:12651)
    at execEmbeddedViewsAction (core.es5.js:12609)
`
The pull-down is rendered.  It responds to initial click by pulling-down, and is otherwise unresponsive.
Have A2JSF 0.4.0-alpha.16 and rxjs (with startWith) 5.4.1.

Maybe something dumb on my end, but I can't see it.
Helpl!
John

**Comment by FoundryFounder** [comment] 2017-07-07 16:36
Seems that including Material solves the issue.

I thought that Material was not necessarily required, but it looks like it might be for an enum.   Not sure.

**Comment by FelschR** [comment] 2017-07-18 11:10
You can also set the attribute `framework="no-framework"`.
It seems the default is `material-design`.

**Comment by Dedac** [comment] 2017-07-20 18:41
@FoundryFounder Can you expound on "including Material"?

**Comment by JKing-B16** [comment] 2017-08-08 22:53
I'm seeing the same issue. Has anyone else figured out the cause?

**Comment by ralph-hm** [comment] 2017-08-28 12:19
Same issue here. Has anyone resolved this issue yet?

**Comment by danmana** [comment] 2017-08-31 11:51
Try adding `import 'rxjs/add/operator/startWith';` to your components which use json-schema-form, it worked for me.

**Comment by dschnelldavis** [comment] 2017-10-24 19:06
Yes, unfortunately, a current limitation of this library is that it requires the [`@angular/material`](https://www.npmjs.com/package/@angular/material) and [`@angular/cdk`](https://www.npmjs.com/package/@angular/cdk) packages be installed, even if you only want to display your form using the Bootstrap framework. This will be fixed in a future version, and until then is being tracked as bug #67 .

**Closed by dschnelldavis** 2017-10-24 19:06 UTC
Labels: bug
