### ISSUE TITLE
Do you have any example for the lazyload?

### ISSUE THREAD

**Issue by lvdream** [dschnelldavis/angular2-json-schema-form#48] opened 2017-06-01 15:44 UTC
in my case, some of my page are using the lazy-load, but when i imported the `JsonSchemaFormModule` into my module, i will meet the error message about `the BrowserModule is already loaded`, i am ensure that other modules are in the same way, but the  browsermodule Error is not appeared.
so do you having any solutions in my case?

ps: i had import the BrowserModule in the `app.module.ts` and import the `CommonModule` in other sub modules

thanks a lot

**Comment by Thorski** [comment] 2017-06-08 20:06
Hello,

I am having this same issue.   If I use lazy loading on a module that uses 
JsonSchemaFormModule, then I get the error:
    ERROR Error: Uncaught (in promise): Error: BrowserModule has already been 
    loaded. If you need access to common directives such as NgIf and NgFor from 
    a lazy loaded module, import CommonModule instead.

I have made a very simple example to demonstrate.   

BrowserModule is only imported from my app.module.ts.

Routing:
  {path: 'lazy', loadChildren: './components/lazy/lazy.module#LazyModule' },

LazyModule imports JsonSchemaFormModule and lists it in its imports.

I like a2jsf a lot, thank you for doing and sharing it :)   But I would like to use it 
in lazy loading scheme.   

Please let me know if this is possible.

-- Thor

**Comment by Thorski** [comment] 2017-06-09 19:23
Here is a plunker showing Lazy Load not working with the above error:
  http://embed.plnkr.co/Tw8yC3i35spcoTG8hQSg/

Click on 'Lazy' and then look at the console :)   The 'Not Lazy' works fine.

**Comment by qazq** [comment] 2017-06-12 06:09
I am having this same issue.

**Comment by alexandreaniceto** [comment] 2017-06-12 13:17
Same issue here...

**Comment by Thorski** [comment] 2017-06-13 17:51
Hi, David Schnell-Davis.

The problem is in the Material Design Framework.   In the file
  material-design-framework.module.ts
the BrowserAnimationsModule is imported.   BrowserAnimationsModule
imports BrowserModule.   Only one copy of BrowserModule is allowed and should
only be imported at the root module.

If I comment out this import, then my example works (on my local machine where I have
a copy of your git repository code).

Can you fix this and release it?  

Thank you!

**Comment by FelschR** [comment] 2017-07-18 11:03
Hmm, I just removed lazy loading from my app because it's just a prototype anyways but I'll probably need this library to work with lazy loading later.

**Comment by nxtjinzhi** [comment] 2017-08-25 08:31
same issue

**Comment by dschnelldavis** [comment] 2017-09-18 05:15
Unfortunately, I don't have much experience lazy loading modules, and I don't have an example.

Recent versions of this library have reduced the number of required dependencies, though I don't know if that's enough to solve this problem.

However, lazy-loading is a feature I would like to support.

Could someone post a repository with an example of what you're trying to do, so I can see exactly the problem you're running into?

I expect that sometime soon we'll be dividing this library into parts, so the core library can be loaded separately from the frameworks, which means that even if a framework, like Material Design, can't be lazy-loaded, perhaps at least the core library can be.

**Comment by Thorski** [comment] 2017-09-18 12:53
Lazy loading was fixed by the fix to material-design-framework.module.ts where it had imported the BrowserAnimationsModule.

**Comment by Thorski** [comment] 2017-09-18 13:03
I also had posted a simple plunker example of the lazy load problem here: 
  http://embed.plnkr.co/Tw8yC3i35spcoTG8hQSg/
It just hangs now though I don't know why.

**Comment by Thorski** [comment] 2017-11-01 11:28
This was fixed for me by #68 .

**Comment by dschnelldavis** [comment] 2017-11-01 16:31
@Thorski 
Thanks for the update. I don't currently have a good way to test lazy loading. So I'll close this for now, but it happens again, please post again so I can re-open it and take a closer look.

**Closed by dschnelldavis** 2017-11-01 16:31 UTC
Labels: enhancement
