### ISSUE TITLE
"allOf" tag does not work when used to extend existing schema.

### ISSUE THREAD

**Issue by sirockin** [dschnelldavis/angular2-json-schema-form#126] opened 2017-10-24 10:22 UTC
Probably related to https://github.com/dschnelldavis/angular2-json-schema-form/issues/112

"allOf" tag does not work as per this sample code, which is the standard pattern for extending one schema with another:
```
{
  "schema":{
    "definitions": {
      "base":
      {
        "required": ["name"],
        "properties": 
        {
          "name":{"type":"string", "default":"hello world!"}
        }
      }
    },
    "allOf":[
      {"$ref":"#/definitions/base"},
      {
        "properties": 
        {
          "foo":{"type":"boolean", "default":false}
        }
      }
    ] 
  }
}
```

**Comment by dschnelldavis** [comment] 2017-10-24 17:09
Actually, this pattern should work.

OneOf and anyOf will need their own special widget, but allOf is already supported, and as long as the properties of the schemas being merged don't conflict, it should render correctly.

However, it appears you've found a bug in the algorithm that merges allOf schemas.

Thanks for posting the example. I'll look into it.

**Comment by dschnelldavis** [comment] 2017-10-24 17:53
Never mind. The allOf merging algorithm is working fine. The problem is that your schema doesn't have a "type" property.

(In some cases, angular2-json-schema-form will add `"type": "object"` to a schema, but only if it sees a `"properties"` key at the root level of the schema, which this schema doesn't have.)

To make this schema render correctly, just add `"type": "object"`, like so:
```javascript
{
  "schema": {
    "type":"object",
    "definitions": {
      "base": {
        "properties": {
          "name": { "type":"string", "default":"hello world!" }
        }
        "required": ["name"],
      }
    },
    "allOf": [
      { "$ref": "#/definitions/base" },
      {
        "properties": {
          "foo": { "type":"boolean", "default":false }
        }
      }
    ] 
  }
}
```

**Closed by dschnelldavis** 2017-10-24 17:53 UTC
Labels: question
